CREATE TABLE books(
  id INTEGER GENERATED ALWAYS AS INDENTITY PRIMARY KEY,
  publish_date DATE,
  archived BOOLEAN,
  publisher TEXT,
  cover_state TEXT,
);

CREATE TABLE labels(
  id INTEGER GENERATED ALWAYS AS INDENTITY PRIMARY KEY,
  title TEXT,
  color TEXT,
);